import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Topbar } from "@repo/ui/topbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Ecom Site",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" id="html" className="h-full bg-white dark:bg-black dark">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Topbar/>
        {children}
      </body>
    </html>
  );
}
